#server:
#  port: 8080
#spring:
#  application:
#    name: client

#eureka:
#  client:
#    healthcheck:
#      enabled: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#        registerWithEureka: true
#        fetchRegistry: true
#    enabled: false
#  instance:
#    preferIpAddress: true
#    hostname: localhost